<a href="https://colab.research.google.com/github/SIVASHANKARI04/Customer-Purchase-Analytics/blob/main/sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/shopping_trends.csv")

In [3]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

#1.What are the columns, data types, and shape of the dataset?

In [4]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Payment Method',
       'Shipping Type', 'Discount Applied', 'Promo Code Used',
       'Previous Purchases', 'Preferred Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

In [6]:
df.shape

(3900, 19)

#2.Are there any missing values? If so, which columns have them?

In [8]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

#3.What are the minimum, maximum, mean, and median values for numerical columns (e.g., purchase amount)?

In [22]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [23]:
df.median(numeric_only=True)

Customer ID              1950.5
Age                        44.0
Purchase Amount (USD)      60.0
Review Rating               3.7
Previous Purchases         25.0
dtype: float64

#4.How many unique values are there in each categorical column?

In [24]:
df["Category"].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [26]:
df["Category"].nunique()

4

#5.Find all purchases greater than a specific amount (e.g., $95).

In [35]:
df[df["Purchase Amount (USD)"] > 95].loc[:,["Purchase Amount (USD)"]]

      Purchase Amount (USD)
8                        97
42                      100
79                       96
81                       96
91                       99
...                     ...
3819                     99
3837                    100
3864                     99
3871                     97
3877                     96

[248 rows x 1 columns]

#6.Filter data for customers from a specific location or category

In [39]:
df[(df["Location"]=="Oregon") & (df["Category"]=="Clothing")].loc[:,["Location","Category"]]

     Location  Category
4      Oregon  Clothing
304    Oregon  Clothing
335    Oregon  Clothing
518    Oregon  Clothing
643    Oregon  Clothing
713    Oregon  Clothing
855    Oregon  Clothing
934    Oregon  Clothing
1044   Oregon  Clothing
1176   Oregon  Clothing
1180   Oregon  Clothing
1215   Oregon  Clothing
1267   Oregon  Clothing
1283   Oregon  Clothing
1353   Oregon  Clothing
1528   Oregon  Clothing
1677   Oregon  Clothing
2101   Oregon  Clothing
2162   Oregon  Clothing
2204   Oregon  Clothing
2396   Oregon  Clothing
2433   Oregon  Clothing
2650   Oregon  Clothing
2830   Oregon  Clothing
2915   Oregon  Clothing
3003   Oregon  Clothing
3073   Oregon  Clothing
3105   Oregon  Clothing
3108   Oregon  Clothing
3167   Oregon  Clothing
3242   Oregon  Clothing
3281   Oregon  Clothing
3390   Oregon  Clothing
3426   Oregon  Clothing
3500   Oregon  Clothing
3549   Oregon  Clothing
3712   Oregon  Clothing

#7.What is the total purchase amount grouped by category?

In [40]:
df.groupby("Category")['Purchase Amount (USD)'].sum()

Category
Accessories     74200
Clothing       104264
Footwear        36093
Outerwear       18524
Name: Purchase Amount (USD), dtype: int64

#8.Find the average purchase amount per product category.

In [41]:
df.groupby("Category")['Purchase Amount (USD)'].mean()

Category
Accessories    59.838710
Clothing       60.025331
Footwear       60.255426
Outerwear      57.172840
Name: Purchase Amount (USD), dtype: float64

#9.Retrieve rows where the category is either "Accessories" or"Outerwear".

In [47]:
df[(df["Category"]=="Accessories") | (df["Category"]=="Outerwear")].value_counts()

Customer ID  Age  Gender  Item Purchased  Category     Purchase Amount (USD)  Location        Size  Color     Season  Review Rating  Subscription Status  Payment Method  Shipping Type   Discount Applied  Promo Code Used  Previous Purchases  Preferred Payment Method  Frequency of Purchases
9            26   Male    Coat            Outerwear    97                     West Virginia   L     Silver    Summer  2.6            Yes                  Venmo           Express         Yes               Yes              8                   Venmo                     Annually                  1
2544         27   Male    Scarf           Accessories  56                     West Virginia   L     Peach     Spring  2.7            No                   Debit Card      Next Day Air    No                No               30                  PayPal                    Bi-Weekly                 1
2599         64   Male    Backpack        Accessories  86                     Nevada          XL    Olive     Fall    3.3            No                   Credit Card     Express         No                No               31                  Debit Card                Annually                  1
2598         60   Male    Jewelry         Accessories  25                     Alabama         XL    Teal      Summer  4.4            No                   Bank Transfer   Store Pickup    No                No               13                  Venmo                     Bi-Weekly                 1
2592         40   Male    Jacket          Outerwear    61                     New Mexico      S     Olive     Spring  3.3            No                   Debit Card      Express         No                No               40                  Cash                      Quarterly                 1
                                                                                                                                                                                                                                                                                                    ..
1287         40   Male    Gloves          Accessories  49                     West Virginia   L     Yellow    Winter  4.9            No                   Bank Transfer   Next Day Air    Yes               Yes              44                  Debit Card                Fortnightly               1
1286         64   Male    Gloves          Accessories  99                     North Carolina  M     Charcoal  Fall    3.5            No                   Venmo           Next Day Air    Yes               Yes              45                  Bank Transfer             Fortnightly               1
1282         29   Male    Belt            Accessories  81                     New Jersey      M     Olive     Spring  4.5            No                   Cash            Store Pickup    Yes               Yes              8                   Venmo                     Bi-Weekly                 1
1275         54   Male    Hat             Accessories  73                     Missouri        M     Olive     Spring  3.1            No                   Cash            2-Day Shipping  Yes               Yes              37                  PayPal                    Quarterly                 1
3900         52   Female  Handbag         Accessories  81                     California      M     Beige     Spring  3.1            No                   Bank Transfer   Store Pickup    No                No               33                  Venmo                     Quarterly                 1
Name: count, Length: 1564, dtype: int64

#10.Sort the dataset by purchase_amount in descending order.

In [48]:
df.sort_values(by=["Purchase Amount (USD)"],ascending=False)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
2842,2843,28,Female,Coat,Outerwear,100,Arizona,L,Green,Fall,4.3,No,Cash,Standard,No,No,48,Debit Card,Quarterly
95,96,37,Male,Sneakers,Footwear,100,Missouri,L,Pink,Fall,3.8,Yes,PayPal,Free Shipping,Yes,Yes,48,PayPal,Monthly
581,582,32,Male,Sweater,Clothing,100,Iowa,XL,Charcoal,Winter,2.7,Yes,Credit Card,Store Pickup,Yes,Yes,12,Bank Transfer,Every 3 Months
1421,1422,68,Male,Dress,Clothing,100,Pennsylvania,S,Gold,Spring,3.0,No,Credit Card,Standard,Yes,Yes,24,Bank Transfer,Fortnightly
3837,3838,45,Female,Hoodie,Clothing,100,New Mexico,M,Green,Spring,4.8,No,Debit Card,Free Shipping,No,No,33,Bank Transfer,Fortnightly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1704,1705,56,Male,Sneakers,Footwear,20,Idaho,M,Lavender,Summer,3.9,No,Bank Transfer,Store Pickup,No,No,19,Cash,Every 3 Months
294,295,70,Male,Skirt,Clothing,20,New Jersey,M,Gold,Spring,4.6,Yes,Cash,Store Pickup,Yes,Yes,19,Credit Card,Every 3 Months
977,978,20,Male,Belt,Accessories,20,Washington,M,Black,Spring,4.6,Yes,Credit Card,Express,Yes,Yes,34,Cash,Bi-Weekly
508,509,27,Male,Jewelry,Accessories,20,Illinois,S,Yellow,Winter,3.7,Yes,Cash,Store Pickup,Yes,Yes,31,PayPal,Quarterly
2798,2799,52,Female,Hoodie,Clothing,20,Rhode Island,XL,Red,Winter,4.8,No,Credit Card,Store Pickup,No,No,37,PayPal,Weekly